### ISSUE TITLE
Mac path & M1 Silicone Macs

### ISSUE THREAD

**Issue by macuserguru** [kuba160/ddb_discord_presence#14]
Which path is ok?
`~/Library/Application Support/Deadbeef/`
or
`~/Library/Application Support/Deadbeef/Plugins`

Are this plugin Apple Silicone CPU ready?

**Comment by kuba160** [comment]
I don't think custom plugins that are published are compatible with Apple processors. With some changes it would be possible to add support to it I think.
I'm not mac user, but from https://deadbeef.sourceforge.io/plugins.html it says that the right directory should be  `~/Library/Application Support/Deadbeef/Plugins`.
This site is missing information about Apple Silicon, I will ask the developer to maybe include it so that the answer is more obvious.

**Comment by kuba160** [comment]
I added macOS build that should work on apple silicon, I have no means of testing it so feedback would be appreciated. You can download `macos-arm64-eb49dc1` build here: https://github.com/kuba160/ddb_discord_presence/actions/runs/6748479365

**Comment by mfpole** [comment]
Hi kuba160, 

Thank you so much for this plug-in. Is it possible to re-run that output? I tried downloading from there but it says "expired". I am also looking for Apple Silicon support.

Thanks again,
-james
