### ISSUE TITLE
[Suggestion/Question] Artwork Support

### ISSUE THREAD

**Issue by UnduGT** [kuba160/ddb_discord_presence#8]
I don't know if that's possible with Discords Rich Presence, but if yes, wouldn't it be great if instead of the DeaDBeeF logo the artwork of the Mp3 file could be seen? Maybe with a little DeaDBeeF logo in the corner. Of course adjustable whether you want it or not.

**Comment by kuba160** [comment]
Unfortunately Discord only supports images as assets, that have to be uploaded on Discord developer page, with maximum of 150 assets. Having artwork would be quite difficult I guess :slightly_smiling_face:

**Comment by TheLastZombie** [comment]
Old issue, but Discord seems to support image URLs in place of asset IDs now (although this is still undocumented). I played around with this today and created [this](https://github.com/TheLastZombie/ddbrpcimg). I don't know how to C, so it's more of a hack than anything (it uses covers from Last.fm instead of the files and requires a server to proxy requests to the Last.fm API), but it seems to work reasonably well.

![image](https://user-images.githubusercontent.com/8181990/153084543-ccba2217-03a2-4184-9009-b1b59e868044.png)

**Comment by kuba160** [comment]
Thank you very much for letting me know! You put much effort into it, I'll add lastfm cover as an option to this plugin soon (actually just did but I will need to clean it up and it is possible that deadbeef plugin builder will require some adjustments as well).

![image](https://user-images.githubusercontent.com/6359901/153098034-f319c927-66ef-46a5-a785-7ca4007ad1d8.png)
